### ISSUE TITLE
请问这个项目有开源相关工具吗?

### ISSUE THREAD

**Issue by winezer0** [v8blink/Chromium-based-XSS-Taint-Tracking#1]
请问这个项目有开源相关工具吗?

我在好几个地方看到这个文章

**Comment by v8blink** [comment]
你好，目前正在进行内测，预计 5 月 20 号在 github 公开，就在这里。

**Comment by v8blink** [comment]
具体最新的动态请关注我的知乎



知乎：https://www.zhihu.com/people/v8blink
我是灰豆，正在努力做一名V8源码的朗读者
 
发件人： WINEZERO
发送时间： 2022-05-13 09:27
收件人： v8blink/Chromium-based-XSS-Taint-Tracking
抄送： Subscribed
主题： [v8blink/Chromium-based-XSS-Taint-Tracking] 请问这个项目有开源相关工具吗? (Issue #1)
请问这个项目有开源相关工具吗?
我在好几个地方看到这个文章

**Comment by winezer0** [comment]
好的，但我不使用知乎，已关注本项目github，期待您的更新
